# Site settings
title: Naturopathe à Paris, Chatou et alentours
email: magali@manebilliet.com
description: Naturopathie, consultation en cabinet ou à domicile, massage bien-être ou drainant, conférences et ateliers gestion du stress en entreprise ou pour particuliers...
url: 'https://www.manebilliet.fr'
author:
twitter:
  username: 33magmag
  card: summary
facebook:
  app_id:
  publisher:
  admins:
logo:
social:
  name: Naturopathe à Paris, Chatou et alentours
  links:
    - https://twitter.com/33magmag
    - https://www.facebook.com/Magali-Mane-Billiet-Naturopathe-258773195014938
lang: fr_FR
permalink: /:title
doctolib:
  link: https://www.doctolib.fr/naturopathe/paris/magali-billiet?utm_medium=referral&amp;utm_campaign=website-button&amp;utm_content=option-1&amp;utm_term=magali-billiet&amp;utm_source=magali-billiet-website-button
timezone: Europe/Paris

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Build settings
#markdown: kramdown
