# Site settings
title: Naturopathe à Paris, Chatou et alentours - Magali Mâne-Billiet
email: magali@manebilliet.com
description: Naturopathie, consultation en cabinet ou à domicile, massage bien-être ou drainant, conférences et ateliers gestion du stress en entreprise ou pour les particuliers...
url: 'https://www.manebilliet.fr'

# Build settings
#markdown: kramdown
