# Site settings
title: Naturopathe à Chatou (78400), Paris (75), Yvelines (78), Hauts-de-Seine (92) et alentours
email: magali@manebilliet.com
description: Naturopathie, consultation en cabinet ou à domicile, massage bien-être ou drainant, conférences et ateliers gestion du stress en entreprise ou pour particuliers. Naturopathe en région Ile-de-France, dans les départements des Yvelines (78), des Hauts-de-Seine (92).
url: 'https://www.manebilliet.fr'
author:
  name: Magali MANE-BILLIET
  picture: /naturopathe.jpg
  twitter: 33magmag
twitter:
  username: 33magmag
  card: summary
facebook:
  app_id:
  publisher:
  admins:
image: /naturopathe.jpg
logo: /naturopathe.jpg
social:
  name: Naturopathe à Chatou et alentours, Naturopathe à Paris
  links:
    - https://twitter.com/33magmag
    - https://www.facebook.com/Magali-Mane-Billiet-Naturopathe-258773195014938
lang: fr_FR
permalink: /:title
doctolib:
  link: https://www.therapeutes.com/naturopathe/chatou/magali-mane-billiet-3971/prenez-un-rdv
timezone: Europe/Paris

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Makefile
  - CNAME
